# This is the component config file, it controls several aspects of the library & doc build process

# shared
# setting these options to false will prevent inclusion of non-component CSS helper classes & scss mixins
# Some of the components have dependencies on these shared imports
shared:
  - utils:          true
  - fonts:          true
  - accessibility:  true
  - animation:      true
  - space:          true
  - bubbles:        true
  - typography:     true

# components
# setting these options to false will:
#   prevent inclusion of components in the compiled library.css
#   hide component examples from the component-sinks test page
components:
  - icon:           true
  - button:         true
  - button_group:   true
  - container:      true
  - data_table:     true
  - form:           true
  - list_group:     true
  - long_form_text: true
  - modal:          true
  - notification:   true
  - pagination:     true
  - popover:        true # Depends on shared/bubbles
  - range_slider:   true
  - switch:         true
  - tooltip:        true # Depends on shared/bubbles

