name: 'Chromatic'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
      - run: |
          npx lerna bootstrap
      - run: |
          npm run --prefix ./test/storybook vrt
